################################################################
# Travis CI Configuration file for Xilinx Readback Verification
# Created by Luke Hsiao
# 30 March 2015
################################################################
language: c
compiler:
  - gcc
#  - clang

# Run Unit Tests
script: cd tests && make
  
notifications:
  email: false  
