################################################################
# Travis CI Configuration file for Xilinx Readback Verification
# Created by Luke Hsiao
# 30 March 2015
################################################################
language: c

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "dkK7mH4ggZR2T3yplmObpg"
    
compiler:
  - gcc
  - clang

# Run Unit Tests
script: cd tests && make
  
notifications:
  email: false  

addons:
  coverity_scan:

    # GitHub project metadata
    project:
      name: lukehsiao/Xilinx_Readback_Verify
      version: 1.0
      description: Tool for verifying readback data.

    # Commands to prepare for build_command
    build_command_prepend: cd src

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    # ** likely specific to your build **
    build_command: make

    # Pattern to match selecting branches that will run analysis.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: master
