################################################################
# Travis CI Configuration file for Xilinx Readback Verification
# Created by Luke Hsiao
# 30 March 2015
################################################################
language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./configure && make
  
notifications:
  email: false  
